module_name: Date of Delivery
compatible_versions: 1.0.0+
author: thirty bees
category: shipping
tags:
  - shipping
  - delivery
  - estimated delivery
description_short: The date of delivery module allows you to set a date of delivery on your orders for customer to see.
description: description.md
images:
  - image-1.png
license: AFL